// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AreaSelector: typeof import('./src/component/AreaSelector.vue')['default']
    CsPostForm: typeof import('./src/component/cs/CsPostForm.vue')['default']
    CsPostList: typeof import('./src/view/CsPostList.vue')['default']
    CsWrite: typeof import('./src/view/CsWrite.vue')['default']
    HomeView: typeof import('./src/view/HomeView.vue')['default']
    IoSider: typeof import('./src/component/IoSider.vue')['default']
    LayoutView: typeof import('./src/view/LayoutView.vue')['default']
    LocateAppendModal: typeof import('./src/component/LocateAppendModal.vue')['default']
    LoginPage: typeof import('./src/view/LoginPage.vue')['default']
    LogoImage: typeof import('./src/component/LogoImage.vue')['default']
    MainView: typeof import('./src/view/MainView.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NP: typeof import('naive-ui')['NP']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    OrderConfirmPayment: typeof import('./src/view/order/OrderConfirmPayment.vue')['default']
    OrderList: typeof import('./src/view/order/OrderList.vue')['default']
    PickLocateManage: typeof import('./src/view/PickLocateManage.vue')['default']
    PickupLocateList: typeof import('./src/component/PickupLocateList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserList: typeof import('./src/view/UserList.vue')['default']
  }
}
